// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWIXtbnxzPELv12buTgwvrZHLQ7nf5608',
    appId: '1:494122341168:web:e46f5cfe16926e1c0b2ef5',
    messagingSenderId: '494122341168',
    projectId: 'roamie5',
    authDomain: 'roamie5.firebaseapp.com',
    storageBucket: 'roamie5.firebasestorage.app',
    measurementId: 'G-6HL7XNJW59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsK1NHxG7uXkRhoggGDPjJdBDYlRud-U',
    appId: '1:494122341168:android:a0e6b92947cac93f0b2ef5',
    messagingSenderId: '494122341168',
    projectId: 'roamie5',
    storageBucket: 'roamie5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWIXtbnxzPELv12buTgwvrZHLQ7nf5608',
    appId: '1:494122341168:web:516ea3c3bea1df920b2ef5',
    messagingSenderId: '494122341168',
    projectId: 'roamie5',
    authDomain: 'roamie5.firebaseapp.com',
    storageBucket: 'roamie5.firebasestorage.app',
    measurementId: 'G-1DR7HCJCYV',
  );
}
